Fix Transaction.sign() calls to include recent_blockhash parameter
- Update send_sol, send_tpc, and mint_tpc functions to pass recent_blockhash to tx.sign()
- Fixes TypeError: Transaction.sign() missing 1 required positional argument: 'recent_blockhash'